# Keep theme config overrides for embedded usage.

base_info:
  title: Byu Blog
  author: Byu.Young

menu: {}

first_screen:
  enable: false

social_contact:
  enable: false

scroll:
  progress_bar: false
  percent: false
  hide_header: true

toc:
  enable: true
  number: false
  expand_all: true
  init_open: true
  layout: right

inject:
  enable: true
  css:
    - /css/embed.css
  js:
    - /js/embed.js
